<div class="row">
	<h2>{{ h2Title|e|e }}</h2>
</div>
<div class="row">
    <form action="ajaxAddUser" method="POST" id="addUser">
    
    	{{ usersForm }}
    	<input type="text" name="{{ name_f_name|e }}" placeholder="{{ ph_f_name|e }}">
        <input type="text" name="{{ name_l_name|e }}" placeholder="{{ ph_l_name|e }}">
        <input type="text" name="{{ name_cc_number|e }}" placeholder="{{ ph_cc_number|e }}">
        <input type="text" name="{{ name_cc_cvv|e }}" placeholder="{{ ph_cc_cvv|e }}">
        <input type="submit" placeholder="GO">
    
    </form>
</div>
<div class="row">
	<p class="response-text" style="visibility: hidden"></p>
</div>

<script>
	$("#addUser").validate({

        rules: {
            {{ name_f_name|e }}: "required",
            
            {{ name_l_name|e }}: "required",
            
            {{ name_cc_number|e }}: {
              required: true,
              creditcard: true
            },
            
            {{ name_cc_cvv|e }}: {
              required: true,
              number: true,
              maxlength: 4
            }
        },
		
		submitHandler: function(form) {

			var options = {
				url: '/ajaxAddUser',
	    		method: 'POST',
	    		data: {
	    			f_name: 	$('{{ name_f_name|e }}').val(), 
	    			l_name: 	$('{{ name_l_name|e }}').val(),
	    			cc_number: 	$('{{ name_cc_number|e }}').val(),
	    			cc_cvv: 	$('{{ name_cc_cvv|e }}').val()
	    		},
	    		success: function(data, statusText, xhr) {
	    
	    			if (xhr.status == 201) {
	    				$('.response-text').text("You'll be redirected to Clients list page.");
	    			} else {
		    			console.log(data);
	    				$('.response-text').text("Something went wrong. You'll be redirected to Form page again.");
	    			}
	    
	    			$('.response-text').css({
	    				visibility: "visible"
	    			});
	    
	    			window.setTimeout(function(){// redirect user after 3 seconds
	    
	    				if (xhr.status != 201) {
	    					alert(data);
	    					window.location.href = "/";
	    				} else {
// 	    					alert(data);
	    					window.location.href = "/ourClients";
	    				}
	    
	    		    }, 3000);
	    		},
	    		error: function(data, statusText, xhr) { 
		    		alert(data.responseText); 
	    		}
			}
			
			$(form).ajaxSubmit(options);
		}
	});
</script>